language: python

python:
  - "3.7"

before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

install:
  - pip install -r requirements.txt
  - pip install -e .K

script:
  - python -m unittest tests.test_main